### ISSUE TITLE
feature(v8) Add other `onDay*` event handlers

### ISSUE THREAD

**Issue by gpbl** [gpbl/react-day-picker#1030]
In v8 we currently support only `onDayClick`. Other events are very common in date pickers and should be added to the `Day` component:

- `onDayMouseEnter`, `onDayMouseLeave`
- `onDayKeyDown`, `onDayKeyUp`, `onDayKeyPress`
- [touch events](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events).

### Notes

* These events are already supported in v7.
* Their signature should be the same as `onDayClick`

### To-do

- [ ] Actually implement the event handlers
- [ ] Add unit-tests
- [ ] Docs: show example, update custom components guide

**Comment by harshilparmar** [comment]
Can I try this issue?
