### ISSUE TITLE
(v8) Verify WCAG are respected

### ISSUE THREAD

**Issue by gpbl** [gpbl/react-day-picker#1036]
We want to make sure that accessibility is correctly implemented in v8.

### To-do

- [ ] Investigate v7 accessibility features and make sure they are in v8 too
- [ ] add unit tests
- [ ] create a report with Lighthouse or other tools
