### ISSUE TITLE
v8 checklist

### ISSUE THREAD

**Issue by gpbl** [gpbl/react-day-picker#779]
I'm collecting some ideas about the next major version. Some rows need to be linked to the relative iessue, et.

- [ ] use [popper.js](https://popper.js.org/) for `DayPickerInput` (fix #765 & al.)
- [ ] remove default exports (#638)
- [ ] build with rollup (need send apologies to @TrySound)
- [ ] adopt [render props pattern](https://reactjs.org/docs/render-props.html) for easier customizing the components
- [ ] add functional tests with test-cafe

**Quick grunts**
- [ ] fix `em` vs `rem` for style (see #777)
- [ ] Replace navbar's CSS background with an actual SVG (#708)
- [ ] Refactor `formatDate`/`parseDate` functions using an object as second argument `({ format, lang})` (similar to date-fns)
- [ ] remove bower
